# Generated by Django 4.2.3 on 2023-07-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
