# Generated by Django 4.2.3 on 2023-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_train_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
