# Generated by Django 4.2.3 on 2023-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_airplane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
